
import React from 'react';

interface DatabaseSetupModalProps {
  onClose: () => void;
}

const DatabaseSetupModal: React.FC<DatabaseSetupModalProps> = ({ onClose }) => {
  const sqlCode = `-- 1. Create profiles table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create messages table
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  content TEXT NOT NULL,
  sender_id UUID REFERENCES auth.users NOT NULL,
  receiver_id UUID REFERENCES auth.users NOT NULL,
  message_type TEXT DEFAULT 'text',
  file_name TEXT,
  is_ai BOOLEAN DEFAULT false
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- 5. Create Policies for Messages
CREATE POLICY "Users can view messages they sent or received." ON messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Users can insert their own messages." ON messages FOR INSERT WITH CHECK (auth.uid() = sender_id);`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlCode);
    alert('SQL copied to clipboard!');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="bg-[#0f172a] border border-white/10 rounded-2xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        <div className="p-4 border-b border-white/5 bg-blue-600 flex items-center justify-between">
          <h3 className="text-sm font-bold uppercase tracking-widest text-white flex items-center gap-2">
            <i className="fas fa-database"></i> Database Setup Required
          </h3>
          <button onClick={onClose} className="text-white/80 hover:text-white">
            <i className="fas fa-times"></i>
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto custom-scrollbar">
          <p className="text-sm text-slate-300 mb-4">
            To use this chat app, you need to create the <code className="bg-slate-800 px-1 rounded text-blue-400">profiles</code> and <code className="bg-slate-800 px-1 rounded text-blue-400">messages</code> tables in your Supabase SQL Editor.
          </p>
          
          <div className="bg-black/40 rounded-xl p-4 border border-white/5 relative group">
            <button 
              onClick={copyToClipboard}
              className="absolute top-4 right-4 bg-slate-800 hover:bg-slate-700 text-[10px] text-white px-3 py-1.5 rounded-lg border border-white/5 transition-all uppercase font-bold"
            >
              <i className="fas fa-copy mr-1"></i> Copy SQL
            </button>
            <pre className="text-[11px] font-mono text-blue-100 overflow-x-auto whitespace-pre leading-relaxed p-2">
              {sqlCode}
            </pre>
          </div>

          <div className="mt-6 space-y-3">
            <h4 className="text-xs font-bold uppercase text-slate-500 tracking-wider">How to apply:</h4>
            <ol className="text-xs text-slate-400 list-decimal pl-4 space-y-2">
              <li>Open your <strong>Supabase Project Dashboard</strong>.</li>
              <li>Click on the <strong>SQL Editor</strong> tab (icon looks like a code block).</li>
              <li>Click <strong>"+ New query"</strong>.</li>
              <li>Paste the code copied from above.</li>
              <li>Click <strong>Run</strong> at the bottom right.</li>
            </ol>
          </div>
        </div>
        
        <div className="p-4 bg-black/20 border-t border-white/5 flex justify-end">
          <button 
            onClick={onClose}
            className="bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold px-6 py-2 rounded-xl transition-all shadow-lg shadow-blue-600/20"
          >
            I've applied the SQL
          </button>
        </div>
      </div>
    </div>
  );
};

export default DatabaseSetupModal;
